user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzk3Mjg=

session:
  key: session_key
  cookie_name: "AIOHTTP_SESSION"
admin:
  email: admin@admin.com
  password: admin
bot:
  token: vk_token
  group_id: 12345